### ISSUE TITLE
No command is working

### ISSUE THREAD

**Issue by castro732** [opencodeco/phpctl#20]
Installed as per the readme instructions, that is runnning the following command:

`wget -q https://phpctl.dev/phpctl-installer.sh && \
bash phpctl-installer.sh && rm phpctl-installer.sh`

If I run for example `phpctl php -m` 
I get 
`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown.`

Every command returns the same.

System specs:
![image](https://github.com/opencodeco/phpctl/assets/1149801/a3389d49-a6fd-4c5e-b135-1f0214f57e7a)

**Comment by flavioheleno** [comment]
Not an _exact_ reproduction, but a similar issue as well:
```shell
$ phpctl php -m
[FATAL tini (7)] exec sh failed: No such file or directory
```

```shell
$ phpctl doctor
PHP_VERSION=82
PHPCTL_DIR=/home/flavio/Documents/../
PHPCTL_IMAGE=opencodeco/phpctl:php82
PHPCTL_RUNTIME=docker
PHPCTL_TTY=-it
PHPCTL_USER=flavio
```

```shell
$ docker -v
Docker version 25.0.2, build 29cf629222
```

```shell
$ uname -a
Linux behemoth 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux
```

```shell
$ bash --version
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)
```

**Comment by leocavalcante** [comment]
Not sure how to reproduce this.
This setup: https://github.com/opencodeco/phpctl/blob/main/tests/install/archlinux.Dockerfile
Works fine: [![asciicast](https://asciinema.org/a/640708.svg)](https://asciinema.org/a/640708)

**Comment by leocavalcante** [comment]
No OP activity.
