### ISSUE TITLE
parallel: command not found

### ISSUE THREAD

**Issue by flavioheleno** [opencodeco/phpctl#37]
The addition of GNU/Parallel (01b9ce7ee97414988fb786ecb588ec2f95f8ad5d) breaks the Makefile in systems that do not have it installed.

```shell
$ make build
/bin/sh: parallel: command not found
make: *** [build] Error 127
```

I suggest either adding a note to README.md or a fallback strategy.

**Comment by leocavalcante** [comment]
Sorry about that. Just added a note to the contribution guidelines: https://github.com/opencodeco/phpctl/blob/main/CONTRIBUTING.md
