### ISSUE TITLE
VALET conflicts, how uninstall? 

### ISSUE THREAD

**Issue by fhferreira** [opencodeco/phpctl#9]
O.S.: Mac Sonoma 14.2.1 (23C71)

when i run: 
**valet start**
the output is:
**Error finding executable PHP. Quitting for safety.
Provided output from find-usable-php.php:
 sh: 32mopencodeco/phpctl:php82: not foundopen input file: Running**

**Comment by fhferreira** [comment]
**composer global require laravel/valet
brew unlink php && brew link --overwrite  php
valet install**

Make it works again

**Comment by fhferreira** [comment]
**phpctl frankenphp**

this didn't works in macos + valet apparently. 

**
Running opencodeco/phpctl:frankenphp
2024/02/01 21:51:40.853 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
2024/02/01 21:51:40.855 WARN    Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies    {"adapter": "caddyfile", "file": "/etc/caddy/Caddyfile", "line": 16}
2024/02/01 21:51:40.856 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2024/02/01 21:51:40.857 INFO    http.auto_https server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2024/02/01 21:51:40.857 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2024/02/01 21:51:40.857 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0002a0c00"}
2024/02/01 21:51:40.859 INFO    FrankenPHP started 🐘   {"php_version": "8.3.1"}
2024/02/01 21:51:40.863 INFO    tls     cleaning storage unit   {"storage": "FileStorage:/data/caddy"}
2024/02/01 21:51:40.863 INFO    tls     finished cleaning storage units
2024/02/01 21:51:40.876 WARN    pki.ca.local    installing root certificate (you might be prompted for password)        {"path": "storage:pki/authorities/local/root.crt"}
2024/02/01 21:51:40.876 ERROR   pki.ca.local    failed to install root certificate      {"error": "open /var/folders/zl/wshf2ff55gx4plj7m5ycw6q40000gn/T/truststore.1013322764.pem: no such file or directory", "certificate_file": "storage:pki/authorities/local/root.crt"}
2024/02/01 21:51:40.876 INFO    http    enabling HTTP/3 listener        {"addr": ":443"}
2024/02/01 21:51:40.876 INFO    failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024/02/01 21:51:40.877 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2024/02/01 21:51:40.877 INFO    http.log        server running  {"name": "remaining_auto_https_redirects", "protocols": ["h1", "h2", "h3"]}
2024/02/01 21:51:40.877 INFO    http    enabling automatic TLS certificate management   {"domains": ["localhost"]}
2024/02/01 21:51:40.878 INFO    autosaved config (load with --resume flag)      {"file": "/config/caddy/autosave.json"}
2024/02/01 21:51:40.878 INFO    serving initial configuration
2024/02/01 21:51:40.878 INFO    tls.obtain      acquiring lock  {"identifier": "localhost"}
2024/02/01 21:51:40.880 INFO    tls.obtain      lock acquired   {"identifier": "localhost"}
2024/02/01 21:51:40.880 INFO    tls.obtain      obtaining certificate   {"identifier": "localhost"}
2024/02/01 21:51:40.882 INFO    tls.obtain      certificate obtained successfully       {"identifier": "localhost"}
2024/02/01 21:51:40.882 INFO    tls.obtain      releasing lock  {"identifier": "localhost"}
2024/02/01 21:51:40.883 WARN    tls     stapling OCSP   {"error": "no OCSP stapling for [localhost]: no OCSP server specified in certificate", "identifiers": ["localhost"]}
**

**Comment by fhferreira** [comment]
**phpctl server 8000 ./public**
_Running opencodeco/phpctl:php82
[Thu Feb  1 21:56:35 2024] PHP 8.2.15 Development Server (http://0.0.0.0:8000) started_

Chrome show as: ERR_CONNECTION_REFUSED

**http://127.0.0.1:8000
http://localhost:8000**

**Comment by leocavalcante** [comment]
It seems that the `phpctl` running image output is conflicting with what Valet expects for `php` command output.
It expects that the output from `php find-usable-php.php` is a file: https://github.com/laravel/valet/blob/master/valet#L28-L31
But the `phpctl` output fuzzies the script output with the `Running: image name` thing: https://github.com/laravel/valet/blob/master/find-usable-php.php

You can workaround this setting the `PHP_EXECUTABLE` environment variable, so the the `valet` script will not need to find one by itself: https://github.com/laravel/valet/blob/master/valet#L26

Please, try again with:
```shell
PHP_EXECUTABLE=/usr/local/bin/php valet start
```

**Comment by leocavalcante** [comment]
About the
```shell
phpctl frankenphp
```
I'm not sure why did you think it didn't worked.
The output looks fine/expected. It is just `INFO`s and a `WARN` here and there, but not errors.

**Comment by leocavalcante** [comment]
I was able to reproduce the
```shell
phpctl server 8000 ./public
```
Problem and moved to a proper issue.
Thanks for reporting!

**Comment by leocavalcante** [comment]
I've moved the FrankenPHP issue to a new issue as well. They are 3 different things.
But please, confirm that it is really not working.
